name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest discover tests
    - name: Build Docker image
      run: docker build -t sales-pipeline .
    - name: Push Docker image
      run: |
        docker tag sales-pipeline:latest myrepo/sales-pipeline:latest
        docker push myrepo/sales-pipeline:latest